# Generated by SlnToQt

TEMPLATE = app
TARGET = LuminEditor

QT += core quick quickdialogs2 widgets

# Defines
DEFINES += \
    QT_QUICK_LIB

# Include paths
INCLUDEPATH += \
    $$PWD/ThirdParty/qmarkdowntextedit

# Sources
# Source Files
SOURCES += \
    main.cpp \
    Src/LMarkdownView.cpp
# ThirdParty
SOURCES += \
    ThirdParty/qmarkdowntextedit/markdownhighlighter.cpp \
    ThirdParty/qmarkdowntextedit/qmarkdowntextedit.cpp \
    ThirdParty/qmarkdowntextedit/qownlanguagedata.cpp \
    ThirdParty/qmarkdowntextedit/qplaintexteditsearchwidget.cpp

# Headers
# Header Files
HEADERS += \
    Src/LMarkdownView.h
# ThirdParty
HEADERS += \
    ThirdParty/qmarkdowntextedit/markdownhighlighter.h \
    ThirdParty/qmarkdowntextedit/qmarkdowntextedit.h \
    ThirdParty/qmarkdowntextedit/qownlanguagedata.h \
    ThirdParty/qmarkdowntextedit/qplaintexteditsearchwidget.h \
    ThirdParty/qmarkdowntextedit/linenumberarea.h

# Forms
# Form Files
FORMS += \
    ThirdParty/qmarkdowntextedit/qplaintexteditsearchwidget.ui

# Resources
# Resource Files
RESOURCES += \
    qml.qrc
# ThirdParty
RESOURCES += \
    ThirdParty/qmarkdowntextedit/media.qrc

